// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1HULDhud4oIesPJerZeatbP75hMXpDk',
    appId: '1:740891297871:web:4941fe17ed3daaee23c23a',
    messagingSenderId: '740891297871',
    projectId: 'exam-project-fd24a',
    authDomain: 'exam-project-fd24a.firebaseapp.com',
    storageBucket: 'exam-project-fd24a.firebasestorage.app',
    measurementId: 'G-S9DBV20K6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYoYIaAmsI0MzthHowvfoc4O_vHaaKRtU',
    appId: '1:740891297871:android:b2d4eec2553e36ca23c23a',
    messagingSenderId: '740891297871',
    projectId: 'exam-project-fd24a',
    storageBucket: 'exam-project-fd24a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_889At6-hIsRf4zr1_s2w0OTBtUBy864',
    appId: '1:740891297871:ios:b25f2a090cdf995d23c23a',
    messagingSenderId: '740891297871',
    projectId: 'exam-project-fd24a',
    storageBucket: 'exam-project-fd24a.firebasestorage.app',
    iosBundleId: 'com.indianoccean.indianOceanScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_889At6-hIsRf4zr1_s2w0OTBtUBy864',
    appId: '1:740891297871:ios:b25f2a090cdf995d23c23a',
    messagingSenderId: '740891297871',
    projectId: 'exam-project-fd24a',
    storageBucket: 'exam-project-fd24a.firebasestorage.app',
    iosBundleId: 'com.indianoccean.indianOceanScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA1HULDhud4oIesPJerZeatbP75hMXpDk',
    appId: '1:740891297871:web:7c5499ad131e464d23c23a',
    messagingSenderId: '740891297871',
    projectId: 'exam-project-fd24a',
    authDomain: 'exam-project-fd24a.firebaseapp.com',
    storageBucket: 'exam-project-fd24a.firebasestorage.app',
    measurementId: 'G-ZMCH12DZXS',
  );
}
